version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    networks:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}

networks:
  mysql:
    external:
      name: mysql
