version: "3"
services:
  mysql:
    image: mysql/mysql-server:${MYSQL_VERSION}
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    command: "--default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp"
    volumes:
      - mysql-data:/var/lib/mysql:delegated
volumes:
  mysql-data:
